import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { RiskLevel, DimensionScore } from '@/types/assessment';
import { DIMENSION_MAP } from '@/data/dimensions';
import { getRiskColor } from './scoring';

// Extend jsPDF with autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => jsPDF;
  }
}

export function generateFreePDF(
  dimensionScores: DimensionScore[],
  overallRisk: number,
  riskLevel: RiskLevel,
  achieverScore: number,
  orgName: string,
  blindSpots: { title: string; severity: RiskLevel; score: number }[]
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // ===== TITLE PAGE =====
  // Background
  doc.setFillColor(16, 42, 67); // navy-900
  doc.rect(0, 0, pageWidth, 100, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('AI Governance Assessment', pageWidth / 2, 40, { align: 'center' });
  doc.setFontSize(14);
  doc.text('Summary Report', pageWidth / 2, 52, { align: 'center' });

  // Org name
  doc.setFontSize(16);
  doc.text(orgName, pageWidth / 2, 70, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setTextColor(155, 179, 200);
  doc.text(
    `Generated ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`,
    pageWidth / 2,
    82,
    { align: 'center' }
  );

  // ===== OVERALL SCORE =====
  doc.setTextColor(16, 42, 67);
  doc.setFontSize(18);
  doc.text('Overall Risk Score', 20, 120);

  // Score circle
  const riskColor = getRiskColor(riskLevel);
  doc.setFillColor(riskColor);
  doc.circle(50, 150, 20, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(String(overallRisk), 50, 155, { align: 'center' });

  doc.setTextColor(16, 42, 67);
  doc.setFontSize(12);
  doc.text(`Risk Level: ${riskLevel}`, 80, 145);
  doc.text(`Achiever Score: ${achieverScore}/100`, 80, 155);
  doc.setFontSize(9);
  doc.setTextColor(98, 125, 152);
  doc.text('Lower risk score = better governance (0-100 scale)', 80, 165);

  // ===== DIMENSION SCORES TABLE =====
  doc.setTextColor(16, 42, 67);
  doc.setFontSize(16);
  doc.text('Dimension Scores', 20, 190);

  const tableData = dimensionScores.map((ds) => [
    DIMENSION_MAP[ds.key]?.label || ds.key,
    `${ds.score}/100`,
    ds.riskLevel,
    `${DIMENSION_MAP[ds.key]?.weight ? DIMENSION_MAP[ds.key].weight * 100 : 0}%`,
  ]);

  doc.autoTable({
    startY: 195,
    head: [['Dimension', 'Score', 'Risk Level', 'Weight']],
    body: tableData,
    headStyles: {
      fillColor: [16, 42, 67],
      textColor: [255, 255, 255],
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [51, 78, 104],
    },
    alternateRowStyles: {
      fillColor: [240, 244, 248],
    },
    margin: { left: 20, right: 20 },
  });

  // ===== BLIND SPOTS (top 3) =====
  doc.addPage();

  doc.setFillColor(16, 42, 67);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text('Top Blind Spots', 20, 20);

  let yPos = 45;
  const topSpots = blindSpots.slice(0, 3);
  for (const spot of topSpots) {
    doc.setTextColor(16, 42, 67);
    doc.setFontSize(11);
    doc.text(`${spot.severity} (${spot.score}/100)`, 20, yPos);

    doc.setFontSize(10);
    doc.setTextColor(51, 78, 104);
    const lines = doc.splitTextToSize(spot.title, pageWidth - 40);
    doc.text(lines, 20, yPos + 8);

    yPos += 8 + lines.length * 6 + 10;
  }

  // ===== UPGRADE CTA =====
  yPos += 10;
  doc.setFillColor(240, 244, 248);
  doc.roundedRect(20, yPos, pageWidth - 40, 50, 3, 3, 'F');
  doc.setTextColor(16, 42, 67);
  doc.setFontSize(12);
  doc.text('Unlock the Full Report', pageWidth / 2, yPos + 15, { align: 'center' });
  doc.setFontSize(9);
  doc.setTextColor(98, 125, 152);
  const ctaLines = doc.splitTextToSize(
    'Upgrade to Pro for: all blind spots with detailed actions, customized vendor questionnaire (30 questions), industry-specific playbooks, multi-dimensional ROI framework, regulatory compliance checklists, and detailed implementation roadmap.',
    pageWidth - 60
  );
  doc.text(ctaLines, pageWidth / 2, yPos + 25, { align: 'center' });

  // ===== FOOTER =====
  doc.setTextColor(155, 179, 200);
  doc.setFontSize(8);
  doc.text(
    'Generated by AI Governance & ROI Assessment Tool | baltaguilar-tech | Data processed locally',
    pageWidth / 2,
    doc.internal.pageSize.getHeight() - 10,
    { align: 'center' }
  );

  // Save
  doc.save(`AI-Governance-Assessment-${orgName.replace(/\s+/g, '-')}.pdf`);
}
